name: TestDriver.ai / Generate / Playwright

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  statuses: write
  pull-requests: write

jobs:
  gather-test-files:
    name: Setup Test Matrix (./testdriver/*.yml)
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.test_list.outputs.files }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: testdriver/regression-test-developers-link-13953073675-1
      # - name: Find all the markdown files
      #   id: markdown_list
      - name: Find all test files and extract filenames
        id: test_list
        run: |
          FILES=$(ls ./testdriver/*.yml)
          FILENAMES=$(basename -a $FILES)
          FILES_JSON=$(echo "$FILENAMES" | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=files::$FILES_JSON"

  test:
    name: Generate Playwright Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: testdriver/regression-test-developers-link-13953073675-1

      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: 1. /run testdriver/test-developers-link.yml
          create-pr: true
          pr-base: testdriver/regression-test-developers-link-13953073675-1
          pr-title: "TestDriver.ai / Generate Regression / test-developers-link"
          pr-branch: testdriver/regression-test-developers-link-13953073675-1
          pr-test-filename: test-developers-link.test.js
          prerun: |
            echo "Step 1: Installing Playwright globally"
            npm install playwright -g

            echo "Step 3: Installing Playwright dependencies"
            playwright install --with-deps chromium

            echo "Step 4: Generating Playwright script"
            $process = Start-Process -FilePath "npx" -ArgumentList "playwright codegen --target playwright-test --viewport-size=1920,1080 -o testdriver/test-developers-link.test.js ${{ vars.TESTDRIVER_WEBSITE }}" -PassThru
            Write-Output "Started Playwright with PID: $($process.Id)"

            echo "Step 5: Completed"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
