name: TestDriver.ai / Generate / Exploratory

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  exploratory:
    outputs:
      new-pr-branch: testdriver/exploratory-${{ github.run_id }}-${{ github.run_attempt }}
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: 
            1. /generate web 10
            2. /summarize
          prerun: |
            cd $env:TEMP
            npm init -y
            npm install dashcam-chrome
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ vars.TESTDRIVER_WEBSITE }}"
            exit        
          create-pr: true
          pr-title: "TestDriver.ai / Generate Test Plans"
          pr-branch: testdriver/exploratory-${{ github.run_id }}-${{ github.run_attempt }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
