name: TestDriver.ai / Generate / Playwright

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      website-url:
        type: string
        required: true
        description: The URL of the website to test
      pr-branches:
        type: string
        required: true
        description: A JSON array of regression test's branch names
    secrets:
      key:
        required: true
        description: The TestDriver API key
      GH_TOKEN:
        required: true
        description: The GitHub token

permissions:
  actions: read
  contents: write
  statuses: write
  pull-requests: write

jobs:
  gather-test-files:
    name: Setup Test Matrix (./testdriver/*.yml)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(inputs.pr-branches) }}
    outputs:
      test_files: ${{ steps.test_list.outputs.files }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Find all test files and extract filenames
        id: test_list
        run: |
          FILES=$(ls ./testdriver/*.yml)
          FILENAMES=$(basename -a $FILES)
          FILES_JSON=$(echo "$FILENAMES" | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=files::$FILES_JSON"

  test:
    name: Generate Playwright Test - ${{ matrix.test }}
    needs: gather-test-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{ fromJson(needs.gather-test-files.outputs.test_files) }}
        branch: ${{ fromJson(inputs.pr-branches) }}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Extract test name
        id: testname
        run: |
          echo "testname=$(echo ${{ matrix.test }} | sed 's/\.yml$//')" >> $GITHUB_OUTPUT

      - name: Display filename being tested
        run: |
          echo "Running job for file: ${{ matrix.test }}"

      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.key }}
          prompt: 1. /run testdriver/${{ matrix.test }}
          create-pr: true
          pr-base: main
          pr-title: "TestDriver.ai / Generate TestDriver and Playwright / ${{ matrix.branch }} / ${{ steps.testname.outputs.testname }}"
          pr-branch: testdriver/playwright-${{ steps.testname.outputs.testname }}-${{ github.run_id }}-${{ github.run_attempt }}
          pr-test-filename: ${{steps.testname.outputs.testname}}.test.js
          prerun: |

            echo "Debug: Current directory"
            pwd
            echo "Current branch"
            echo ${{ github.ref }}
            echo "Files inside"
            ls -la
            echo "Files in subdirectories"
            ls -la -R

            echo "Step 1: Installing Playwright globally"
            npm install playwright -g

            echo "Step 3: Installing Playwright dependencies"
            playwright install --with-deps chromium

            echo "Step 4: Generating Playwright script"
            $process = Start-Process -FilePath "npx" -ArgumentList "playwright codegen --target playwright-test --viewport-size=1920,1080 -o testdriver/${{ steps.testname.outputs.testname }}.test.js ${{ vars.TESTDRIVER_WEBSITE }}" -PassThru
            Write-Output "Started Playwright with PID: $($process.Id)"

            echo "Step 5: Completed"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
