name: Find Matching Branches

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'The base branch to search in'
        required: true
        default: 'main'

jobs:
  find-matching-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Extract markdown file names
        id: extract
        run: |
          echo "Searching for Markdown files in the testdriver/ folder..."
          # Find all .md files, then remove the directory and extension
          file_names=$(find testdriver -type f -name "*.md" | sed 's|.*/||; s/\.md$//')
          echo "Extracted file names:"
          echo "$file_names"
          # Convert newline-separated file names into a comma-separated list
          file_list=$(echo "$file_names" | paste -sd "," -)
          echo "file_list=$file_list" >> $GITHUB_OUTPUT

      - name: Find branches with file name substrings
        id: matching
        run: |
          # Convert the comma-separated list back to newlines for processing
          file_names=$(echo "${{ steps.extract.outputs.file_list }}" | tr ',' '\n')
          echo "File names to search for in branch names:"
          echo "$file_names"
          matches=""
          for file in $file_names; do
            echo "Searching for remote branches containing: $file"
            # List remote branches that match the file name substring.
            # Note: 'origin/' is removed to get the clean branch name.
            # Use grep with word boundaries to find file name anywhere in branch name
            branch_matches=$(git branch -r | grep -E ".*${file}.*" | sed 's|origin/||' || true)
            if [ -n "$branch_matches" ]; then
              echo "Matches found for '$file':"
              echo "$branch_matches"
              matches="$matches $branch_matches"
            fi
          done
          # Remove duplicates and format as a comma-separated list
          matching_branches=$(echo $matches | tr ' ' '\n' | sort | uniq | paste -sd "," -)
          echo "matching_branches=$matching_branches" >> $GITHUB_OUTPUT
          echo "Matching branches: $matching_branches"

      - name: Output matching branches
        run: |
          echo "The matching branches are: ${{ steps.matching.outputs.matching_branches }}"