name: Find and Generate Playwright Tests

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'The base branch to search in'
        required: true
        default: 'testdriver/exploratory-14080624045-1'
      run_id:
        description: 'The run ID to search for'
        required: true
        default: '14080624045'
      attempt:
        description: 'The attempt number to search for'
        required: true
        default: '1'
jobs:
  find-regression-branches:
    runs-on: ubuntu-latest
    outputs:
      regression_branches: ${{ steps.matching.outputs.regression_branches }}
      test_name: ${{ steps.extract.outputs.file_list_json }}
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Extract markdown file names
        id: extract
        run: |
          FILES=$(ls ./testdriver/generate/*.md)
          FILENAMES=$(basename -a $FILES | sed 's/\.md$//')
          # echo "file_list=$FILENAMES" >> $GITHUB_OUTPUT
          FILES_JSON=$(echo "$FILENAMES" | jq -R -s -c 'split("\n")[:-1]')
          echo "file_list_json=$FILES_JSON" >> $GITHUB_OUTPUT

      - name: Get all the branches
        id: get_branches
        run: |
          git fetch --all
          git branch -r

      - name: Find branches with file name substrings
        id: matching
        run: |
          run_id="${{ github.event.inputs.run_id }}"
          attempt="${{ github.event.inputs.attempt }}"
          # Convert the comma-separated list back to newlines for processing
          file_names=$(echo '${{ steps.extract.outputs.file_list_json }}')
          echo "File names to search for in branch names:"
          echo "$file_names"
          matches=""
          # Iterate through the JSON array
          for file in $(echo "$test_files" | jq -r '.[]'); do
            echo "Searching for remote branches containing pattern: testdriver/regression-$file-$run_id-$attempt"
            # List remote branches that match the exact pattern
            # Note: 'origin/' is removed to get the clean branch name
            pattern="testdriver/regression-${file}-${run_id}-${attempt}"
            branch_matches=$(git branch -r | grep -E "origin/$pattern" | sed 's|origin/||' || true)
            if [ -n "$branch_matches" ]; then
              echo "Matches found for '$file':"
              echo "$branch_matches"
              matches="$matches $branch_matches"
            fi
          done

          # Remove duplicates and format as a JSON array
          matching_branches=$(echo $matches | tr ' ' '\n' | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
          echo "regression_branches=$matching_branches" >> $GITHUB_OUTPUT
          echo "Matching branches: $matching_branches"

  generate-playwright-tests:
    needs: find-regression-branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.find-regression-branches.outputs.regression_branches) }}
        test_name: ${{ fromJson(needs.find-regression-branches.outputs.test_name) }}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: 1. /run testdriver/${{ matrix.test_name }}.yml
          branch: ${{ matrix.branch }}
          create-pr: true
          pr-base: main
          pr-title: "TestDriver.ai / Generate Playwright / ${{ matrix.test_name }}"
          pr-branch: testdriver/playwright-${{ matrix.test_name }}-${{ github.event.inputs.run_id }}-${{ github.event.inputs.attempt }}"
          pr-test-filename: ${{ matrix.test_name }}.test.js
          prerun: |
            echo "Step 1: Installing Playwright globally"
            npm install playwright -g
            echo "Step 3: Installing Playwright dependencies"
            playwright install --with-deps chromium
            echo "Step 4: Generating Playwright script"
            $process = Start-Process -FilePath "npx" -ArgumentList "playwright codegen --target playwright-test --viewport-size=1920,1080 -o testdriver/${{ matrix.test_name }}.test.js ${{ vars.TESTDRIVER_WEBSITE }}" -PassThru

            echo "Generated Playwright script"
            echo "$process"
            echo "Step 5: Completed"
            exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"