name: Trigger Playwright Generation

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'The base branch to search in'
        required: true
        default: 'testdriver/regression-test-try-for-free-button-13973697183-1'

jobs:
  generate-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Extract test file
        id: extract_test_file
        run: |
          TEST_FILE=$(ls ./testdriver/*.yml)
          TEST_FILE=$(basename $TEST_FILE .yml)
          echo "TEST_FILE=$TEST_FILE"
          echo "test_file=$TEST_FILE" >> $GITHUB_OUTPUT

      - name: Trigger Playwright Generation
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          branch: ${{ github.event.inputs.base_branch }}
          prompt: 1. /run testdriver/${{ steps.extract_test_file.outputs.test_file }}.yml
          create-pr: true
          pr-base: main
          pr-title: "TestDriver.ai / Generate Playwright Tests / ${{ steps.extract_test_file.outputs.test_file }}"
          pr-branch: testdriver/playwright-${{ steps.extract_test_file.outputs.test_file }}-${{ github.run_id }}-${{ github.run_attempt }}
          pr-test-filename: ${{ steps.extract_test_file.outputs.test_file }}.test.js
          prerun: |
            echo "Step 1: Installing Playwright globally"
            npm install playwright -g

            echo "Step 3: Installing Playwright dependencies"
            playwright install --with-deps chromium

            echo "Step 4: Generating Playwright script"
            $process = Start-Process -FilePath "npx" -ArgumentList "playwright codegen --viewport-size=1920,1080 --target playwright-test -o testdriver/${{ steps.extract_test_file.outputs.test_file }}.test.js ${{ vars.TESTDRIVER_WEBSITE }}" -PassThru

            echo "Step 5: Completed"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
