name: Trigger Playwright Generation

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'The base branch to search in'
        required: true
        default: 'testdriver/regression-test-try-for-free-button-13973697183-1'

jobs:
  generate-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Extract test file
        id: extract_test_file
        run: |
          TEST_FILE=$(ls ./testdriver/*.yml)
          TEST_FILE=$(basename $TEST_FILE .yml)
          echo "TEST_FILE=$TEST_FILE"
          echo "test_file=$TEST_FILE" >> $GITHUB_OUTPUT

      - name: Trigger Playwright Generation
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          branch: ${{ github.event.inputs.base_branch }}
          prompt: 1. /run testdriver/${{ steps.extract_test_file.outputs.test_file }}.yml
          prerun: |
            cd $env:TEMP
            # Write-Output "Current directory: $(Get-Location)"
            # Write-Output "files in current directory: $(Get-ChildItem -Force)"
            # Write-Output "files in testdriver directory: $(Get-ChildItem -Force ./testdriver/)"
            # # echo "Step 1: Installing Playwright globally"
            # npm install playwright -g
            # echo "Step 3: Installing Playwright dependencies"
            # playwright install --with-deps chromium
            # echo "Step 4: Generating Playwright script"
            # npx playwright codegen --target playwright-test --viewport-size="1920,1080" -o testdriver/playwright.test.js "${{ vars.TESTDRIVER_WEBSITE }}"
            # exit 0
            npm init -y
            npm install dashcam-chrome
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ vars.TESTDRIVER_WEBSITE }}"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
