name: Trigger Playwright Generation

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'The base branch to search in'
        required: true
        default: 'testdriver/regression-test-try-for-free-button-13973697183-1'

jobs:
  generate-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Extract test file
        id: extract_test_file
        run: |
          TEST_FILE=$(ls ./testdriver/*.yml | head -n 1 | xargs basename -s .yml)
          echo "test_file=$TEST_FILE" >> $GITHUB_OUTPUT
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Trigger Playwright Generation
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: 1. /run testdriver/${{ steps.extract_test_file.outputs.test_file }}.yml
          create-pr: true
          pr-base: main
          pr-title: "TestDriver.ai / Generate Playwright / ${{ steps.extract_test_file.outputs.test_file }}"
          pr-branch: testdriver/playwright-${{ steps.extract_test_file.outputs.test_file }}
          pr-test-filename: playwright.test.js
          prerun: |
            echo "Step 1: Installing Playwright globally"
            npm install playwright -g
            echo "Step 3: Installing Playwright dependencies"
            playwright install --with-deps chromium
            echo "Step 4: Generating Playwright script"
            npx playwright codegen --target playwright-test --viewport-size="1920,1080" -o testdriver/playwright.test.js "${{ vars.TESTDRIVER_WEBSITE }}"
            exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
